// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;

namespace Azure.Analytics.Purview.UnifiedCatalog
{
    /// <summary> ModelsFacetRequestObject. </summary>
    public partial class ModelsFacetRequestObject
    {
        /// <summary> Keeps track of any properties unknown to the library. </summary>
        private protected readonly IDictionary<string, BinaryData> _additionalBinaryDataProperties;

        /// <summary> Initializes a new instance of <see cref="ModelsFacetRequestObject"/>. </summary>
        public ModelsFacetRequestObject()
        {
        }

        /// <summary> Initializes a new instance of <see cref="ModelsFacetRequestObject"/>. </summary>
        /// <param name="name"> name. </param>
        /// <param name="additionalBinaryDataProperties"> Keeps track of any properties unknown to the library. </param>
        internal ModelsFacetRequestObject(string name, IDictionary<string, BinaryData> additionalBinaryDataProperties)
        {
            Name = name;
            _additionalBinaryDataProperties = additionalBinaryDataProperties;
        }

        /// <summary> name. </summary>
        public string Name { get; set; }
    }
}
